SELECT RPAD('55',6,'0') FROM DUAL;

SELECT REPLACE('Metin Güncelleme', 'Metin', 'Veri') FROM DUAL;

SELECT REVERSE('muhammettncy.com') FROM DUAL;

SELECT CONCAT('MUHAMMET', ' TUNCAY') AS AD FROM DUAL;

SELECT CHR (79) FROM DUAL;

SELECT 'MUHAMMET ' || 'TUNCAY' | | ' SQL' FROM DUAL;

SELECT UPPER('kodluyoruzsql') FROM DUAL;

SELECT INITCAP('oracle sql seni seviyorum') from dual;	--:D

SELECT SUBSTR('Oracle VeritabanI',2,4) FROM DUAL;

SELECT ASCII('M') from DUAL;

SELECT TRIM('0' FROM '0000000330000000000') AS RESULT FROM DUAL;

SELECT TRIM(TRAILING '0' FROM '0000000330000000000') AS RESULT FROM DUAL;

SELECT RTRIM('------MUHAMMET------', '-') FROM DUAL;

SELECT LTRIM('------MUHAMMET------', '-') FROM DUAL;

SELECT CHR(89) FROM DUAL;

SELECT LOWER('MUHAMMET') FROM DUAL;

SELECT LENGTH('MUHAMMET') FROM DUAL;
